# Generated by Django 5.2.7 on 2025-10-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signalement_photo_alter_signalement_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetPerdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('date_perte', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='objet',
            name='date_trouve',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objet',
            name='lieu_trouve',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
