# Generated by Django 5.2.7 on 2025-10-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_objetperdu_objet_date_trouve_objet_lieu_trouve'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
