# Generated by Django 5.2.7 on 2025-10-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prefecture_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='zone',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prefecture'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.AlterUniqueTogether(
            name='prefecture',
            unique_together={('region', 'nom')},
        ),
    ]
