# Generated by Django 5.2.7 on 2025-11-21 03:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_remove_utilisateur_zone_utilisateur_prefecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declaration', models.CharField(choices=[('PERDU', 'Perdu'), ('TROUVE', 'Trouvé')], max_length=10)),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], db_index=True, default='SOUMIS', max_length=10)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Déclaration',
                'verbose_name_plural': 'Déclarations',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('commissariat', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'ordering': ['region', 'prefecture', 'quartier'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Notification Push'), ('SYSTEME', 'Notification Système')], default='SYSTEME', max_length=10)),
                ('lu', models.BooleanField(db_index=True, default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificatif', models.FileField(help_text='Document justificatif (photo, facture, etc.)', upload_to='justificatifs/')),
                ('description_justificative', models.TextField(help_text="Description expliquant pourquoi l'objet vous appartient")),
                ('statut', models.CharField(choices=[('EN_VERIFICATION', 'En vérification'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('RESTITUTION_PROGRAMMEE', 'Restitution programmée')], db_index=True, default='EN_VERIFICATION', max_length=25)),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('commentaire_verification', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_reclamation'],
                'permissions': [('can_verify_reclamation', 'Peut vérifier une réclamation')],
            },
        ),
        migrations.AlterModelOptions(
            name='objet',
            options={'ordering': ['-dateDeclaration'], 'permissions': [('can_validate_objet', 'Peut valider un objet'), ('can_publish_objet', 'Peut publier un objet')], 'verbose_name': 'Objet', 'verbose_name_plural': 'Objets'},
        ),
        migrations.AlterModelOptions(
            name='objetperdu',
            options={'verbose_name': 'Objet perdu (ancien)', 'verbose_name_plural': 'Objets perdus (anciens)'},
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'ordering': ['region', 'nom'], 'verbose_name': 'Préfecture', 'verbose_name_plural': 'Préfectures'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom'], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_signalement'], 'verbose_name': 'Signalement (ancien)', 'verbose_name_plural': 'Signalements (anciens)'},
        ),
        migrations.AlterModelOptions(
            name='structurelocale',
            options={'ordering': ['prefecture', 'nom'], 'verbose_name': 'Structure locale', 'verbose_name_plural': 'Structures locales'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='objet',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='date_trouve',
        ),
        migrations.RemoveField(
            model_name='objet',
            name='lieu_trouve',
        ),
        migrations.AddField(
            model_name='objet',
            name='agent_responsable',
            field=models.ForeignKey(limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objet',
            name='couleur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='objet',
            name='dateDeclaration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='objet',
            name='datePerte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objet',
            name='est_perdu',
            field=models.BooleanField(default=True, help_text='True=perdu, False=trouvé'),
        ),
        migrations.AddField(
            model_name='objet',
            name='etat',
            field=models.CharField(choices=[('CREE', 'Créé'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('PUBLIE', 'Publié'), ('RECLAME', 'Réclamé'), ('EN_VERIFICATION', 'En vérification'), ('RESTITUE', 'Restitué'), ('REFUSE', 'Refusé')], db_index=True, default='CREE', max_length=20),
        ),
        migrations.AddField(
            model_name='objet',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='objet',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text="Propriétaire de l'objet (null pour objets trouvés)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_proprietaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objet',
            name='typeObjet',
            field=models.CharField(choices=[('TELEPHONE', 'Téléphone'), ('PORTEFEUILLE', 'Portefeuille'), ('CLES', 'Clés'), ('DOCUMENT', 'Document'), ('BIJOU', 'Bijou'), ('VETEMENT', 'Vêtement'), ('AUTRE', 'Autre')], db_index=True, default='AUTRE', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.prefecture'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.region'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('citoyen', 'Citoyen'), ('agent', 'Agent de gestion'), ('admin', 'Administrateur')], db_index=True, default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['role'], name='core_utilis_role_a59af2_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='core_utilis_email_1e7dc9_idx'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='agent_validateur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaration',
            name='objet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='core.objet'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='localisation',
            index=models.Index(fields=['region', 'prefecture'], name='core_locali_region_942c86_idx'),
        ),
        migrations.AddIndex(
            model_name='localisation',
            index=models.Index(fields=['quartier'], name='core_locali_quartie_ac226b_idx'),
        ),
        migrations.AddField(
            model_name='objet',
            name='lieuPerte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objets', to='core.localisation'),
        ),
        migrations.AddIndex(
            model_name='objet',
            index=models.Index(fields=['etat', 'est_perdu'], name='core_objet_etat_14395f_idx'),
        ),
        migrations.AddIndex(
            model_name='objet',
            index=models.Index(fields=['typeObjet'], name='core_objet_typeObj_ec5d08_idx'),
        ),
        migrations.AddIndex(
            model_name='objet',
            index=models.Index(fields=['-dateDeclaration'], name='core_objet_dateDec_c1ac11_idx'),
        ),
        migrations.AddIndex(
            model_name='objet',
            index=models.Index(fields=['datePerte'], name='core_objet_datePer_e460a7_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='agent_verificateur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_verifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.objet'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['statut', '-date_soumission'], name='core_declar_statut_3785ec_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['type_declaration'], name='core_declar_type_de_16d1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'lu', '-date_creation'], name='core_notifi_utilisa_60cc07_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification'], name='core_notifi_type_no_ecb58f_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['statut', '-date_reclamation'], name='core_reclam_statut_a5f651_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['objet', 'statut'], name='core_reclam_objet_i_ee26ad_idx'),
        ),
    ]
