# Generated by Django 5.2.7 on 2025-11-21 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_declaration_localisation_notification_reclamation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objet',
            name='agent_responsable',
            field=models.ForeignKey(limit_choices_to={'role__in': ['agent', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='justificatif',
            field=models.FileField(blank=True, help_text='Document justificatif (photo, facture, etc.)', null=True, upload_to='justificatifs/'),
        ),
    ]
