# Generated by Django 5.2.7 on 2025-11-24 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commentaireanonyme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text='Classe CSS FontAwesome', max_length=50)),
                ('couleur', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal', max_length=7)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Catégorie d'objet",
                'verbose_name_plural': "Catégories d'objets",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='prefecture',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='structurelocale',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('can_manage_declarations', 'Peut gérer les déclarations'), ('can_validate_claims', 'Peut valider les réclamations'), ('can_manage_users', 'Peut gérer les utilisateurs'), ('can_view_analytics', 'Peut voir les analytics'), ('can_manage_regions', 'Peut gérer les régions')]},
        ),
        migrations.AddField(
            model_name='commentaireanonyme',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='structurelocale',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structurelocale',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='structurelocale',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='structurelocale',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='structurelocale',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='verifie',
            field=models.BooleanField(default=False, help_text='Compte vérifié par un admin'),
        ),
        migrations.AlterField(
            model_name='commentaireanonyme',
            name='signalement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_anonymes', to='core.signalement'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='objet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.objet'),
        ),
        migrations.AlterField(
            model_name='structurelocale',
            name='type_structure',
            field=models.CharField(choices=[('commissariat', 'Commissariat'), ('mairie', 'Mairie'), ('gendarmerie', 'Gendarmerie'), ('poste', 'Bureau de poste'), ('autre', 'Autre structure locale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('citoyen', 'Citoyen'), ('agent', 'Agent de gestion'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur')], default='citoyen', max_length=12),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_declaration', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_declaration', models.CharField(choices=[('perdu', 'Objet perdu'), ('trouve', 'Objet trouvé')], max_length=10)),
                ('statut', models.CharField(choices=[('cree', 'Créé'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('publie', 'Publié'), ('reclame', 'Réclamé'), ('en_verification', 'En vérification'), ('restitue', 'Restitué'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='cree', max_length=20)),
                ('nom_objet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='declarations/')),
                ('lieu_precis', models.CharField(help_text='Lieu précis de perte/découverte', max_length=300)),
                ('date_incident', models.DateField(help_text='Date de perte ou de découverte')),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_restitution', models.DateTimeField(blank=True, null=True)),
                ('commentaire_declarant', models.TextField(blank=True)),
                ('commentaire_agent', models.TextField(blank=True, help_text="Commentaire interne de l'agent")),
                ('priorite', models.IntegerField(choices=[(1, 'Normale'), (2, 'Haute'), (3, 'Urgente')], default=1)),
                ('visible_publiquement', models.BooleanField(default=True)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('agent_validateur', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorieobjet')),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_declarations', to=settings.AUTH_USER_MODEL)),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prefecture')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
                ('structure_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.structurelocale')),
            ],
            options={
                'ordering': ['-date_declaration'],
                'permissions': [('can_validate_declaration', 'Peut valider une déclaration'), ('can_publish_declaration', 'Peut publier une déclaration'), ('can_archive_declaration', 'Peut archiver une déclaration')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_conversation', models.CharField(choices=[('declaration', "À propos d'une déclaration"), ('reclamation', "À propos d'une réclamation"), ('general', 'Question générale'), ('support', 'Support technique')], default='general', max_length=15)),
                ('sujet', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('fermee', 'Fermée'), ('archivee', 'Archivée')], default='ouverte', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.IntegerField(choices=[(1, 'Normale'), (2, 'Haute'), (3, 'Urgente')], default=1)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_agent', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_utilisateur', to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.declaration')),
            ],
            options={
                'ordering': ['-date_dernier_message'],
            },
        ),
        migrations.AddField(
            model_name='commentaireanonyme',
            name='declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_anonymes', to='core.declaration'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_interne', models.BooleanField(default=False, help_text='Message interne visible uniquement par les agents')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='declarations/photos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_supplementaires', to='core.declaration')),
            ],
            options={
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_reclamation', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', 'En cours de vérification'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('retiree', 'Retirée par le réclamant')], default='soumise', max_length=15)),
                ('justification', models.TextField(help_text='Pourquoi cet objet vous appartient-il ?')),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_retrait_prevue', models.DateTimeField(blank=True, null=True)),
                ('commentaire_reclamant', models.TextField(blank=True)),
                ('commentaire_agent', models.TextField(blank=True, help_text="Commentaire interne de l'agent")),
                ('motif_rejet', models.TextField(blank=True)),
                ('priorite', models.IntegerField(choices=[(1, 'Normale'), (2, 'Haute'), (3, 'Urgente')], default=1)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('agent_traitant', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agent', 'admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.declaration')),
                ('reclamant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_reclamations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reclamation'],
                'unique_together': {('declaration', 'reclamant')},
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('photo', "Photo de l'objet"), ('facture', "Facture d'achat"), ('garantie', 'Certificat de garantie'), ('identite', "Pièce d'identité"), ('autre', 'Autre document')], max_length=10)),
                ('fichier', models.FileField(upload_to='justificatifs/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('taille_fichier', models.PositiveIntegerField(help_text='Taille en octets')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('verifie', models.BooleanField(default=False)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='core.reclamation')),
            ],
            options={
                'ordering': ['type_piece', 'date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='reclamation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reclamation'),
        ),
        migrations.CreateModel(
            name='StatistiqueRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_declarations', models.PositiveIntegerField(default=0)),
                ('declarations_en_attente', models.PositiveIntegerField(default=0)),
                ('declarations_publiees', models.PositiveIntegerField(default=0)),
                ('objets_restitues', models.PositiveIntegerField(default=0)),
                ('total_reclamations', models.PositiveIntegerField(default=0)),
                ('reclamations_en_cours', models.PositiveIntegerField(default=0)),
                ('reclamations_approuvees', models.PositiveIntegerField(default=0)),
                ('reclamations_rejetees', models.PositiveIntegerField(default=0)),
                ('temps_moyen_traitement_heures', models.FloatField(default=0.0)),
                ('taux_restitution', models.FloatField(default=0.0)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='core.region')),
            ],
            options={
                'verbose_name': 'Statistique région',
                'verbose_name_plural': 'Statistiques régions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('declaration_cree', 'Déclaration créée'), ('declaration_validee', 'Déclaration validée'), ('declaration_rejetee', 'Déclaration rejetée'), ('declaration_publiee', 'Déclaration publiée'), ('nouvelle_reclamation', 'Nouvelle réclamation'), ('reclamation_approuvee', 'Réclamation approuvée'), ('reclamation_rejetee', 'Réclamation rejetée'), ('objet_restitue', 'Objet restitué'), ('nouveau_message', 'Nouveau message'), ('rappel', 'Rappel'), ('systeme', 'Notification système')], max_length=25)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien_action', models.URLField(blank=True, help_text="Lien vers l'action à effectuer")),
                ('lue', models.BooleanField(default=False)),
                ('importante', models.BooleanField(default=False)),
                ('envoyee_par_email', models.BooleanField(default=False)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.declaration')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reclamation')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', '-date_creation'], name='core_notifi_destina_8bb365_idx'), models.Index(fields=['lue', 'destinataire'], name='core_notifi_lue_508d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('declaration_creee', 'Déclaration créée'), ('declaration_validee', 'Déclaration validée'), ('declaration_rejetee', 'Déclaration rejetée'), ('declaration_publiee', 'Déclaration publiée'), ('declaration_archivee', 'Déclaration archivée'), ('reclamation_soumise', 'Réclamation soumise'), ('reclamation_approuvee', 'Réclamation approuvée'), ('reclamation_rejetee', 'Réclamation rejetée'), ('objet_restitue', 'Objet restitué'), ('utilisateur_cree', 'Utilisateur créé'), ('utilisateur_modifie', 'Utilisateur modifié'), ('role_modifie', 'Rôle utilisateur modifié'), ('region_assignee', 'Région assignée'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('erreur', 'Erreur système')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.declaration')),
                ('reclamation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reclamation')),
            ],
            options={
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['utilisateur', '-date_action'], name='core_action_utilisa_010ad9_idx'), models.Index(fields=['action', '-date_action'], name='core_action_action_82937d_idx'), models.Index(fields=['declaration', '-date_action'], name='core_action_declara_79bb99_idx')],
            },
        ),
    ]
