# Generated by Django 5.2.7 on 2025-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categorieobjet_alter_prefecture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('citoyen', 'Citoyen'), ('agent', 'Agent'), ('admin', 'Administrateur')], default='citoyen', max_length=12),
        ),
    ]
