# Generated by Django 5.2.7 on 2025-10-13 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_utilisateur_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='signalement_type',
            field=models.CharField(choices=[('Perdu', 'Perdu'), ('Retrouvé', 'Retrouvé')], default='Perdu', max_length=20),
        ),
        migrations.AddField(
            model_name='signalement',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='lieu',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.objet'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
