# Generated by Django 5.2.7 on 2025-10-15 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_signalement_signalement_type_signalement_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='signalement_type',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='zone',
        ),
        migrations.AlterField(
            model_name='signalement',
            name='lieu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.objet'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('perdu', 'Perdu'), ('trouve', 'Trouvé'), ('retourne', 'Retourné au propriétaire')], default='perdu', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signalement',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prefecture'),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='core.region'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.CreateModel(
            name='StructureLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_structure', models.CharField(choices=[('commissariat', 'Commissariat'), ('mairie', 'Mairie'), ('autre', 'Autre structure locale')], max_length=20)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures_locales', to='core.prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='signalement',
            name='structure_locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.structurelocale'),
        ),
    ]
