# Generated by Django 5.2.7 on 2025-11-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_utilisateur_zone_utilisateur_prefecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireAnonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Votre commentaire (max 1000 caractères)', max_length=1000)),
                ('pseudo', models.CharField(blank=True, help_text="Pseudo optionnel (ou laissez vide pour 'Anonyme')", max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email optionnel (ne sera pas affiché publiquement)', max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_approuve', models.BooleanField(default=True, help_text='Commentaire approuvé pour affichage')),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_anonymes', to='core.signalement')),
            ],
            options={
                'verbose_name': 'Commentaire anonyme',
                'verbose_name_plural': 'Commentaires anonymes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
