# Generated by Django 5.2.7 on 2025-12-03 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_create_chat_tables'),
    ]

    # Cette migration était initialement destinée à créer des modèles de chat.
    # Dans la base actuelle, ces tables existent déjà (migration 0014 ou tables historiques),
    # et appliquer ces CreateModel provoque une erreur "table already exists" lors des tests.
    # Pour rendre l'ensemble idempotent et permettre la création de la base de tests,
    # on conserve une migration no-op (neffectue aucun changement SQL) ici.
    def _noop(apps, schema_editor):
        return None

    operations = [
        migrations.RunPython(_noop, reverse_code=migrations.RunPython.noop),
    ]
