# Generated by Django 5.2.7 on 2026-01-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20251203_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_lecture',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='message',
            name='est_interne',
        ),
        migrations.RemoveField(
            model_name='message',
            name='fichier_joint',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lu',
        ),
        migrations.RemoveField(
            model_name='message',
            name='nom_fichier',
        ),
        migrations.AddField(
            model_name='conversation',
            name='declarant',
            field=models.ForeignKey(blank=True, help_text='Déclarant participant à la conversation', limit_choices_to={'role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_declarant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='signalement',
            field=models.ForeignKey(blank=True, help_text='Signalement concerné par cette conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.declaration'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, help_text='Fichier joint (image, PDF, etc.)', null=True, upload_to='chat_files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Message lu par le destinataire'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Date de lecture du message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Destinataire du message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Expéditeur du message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('texte', 'Message texte'), ('fichier', 'Fichier joint'), ('systeme', 'Message système')], default='texte', help_text='Type de message', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent participant à la conversation', limit_choices_to={'role__in': ['agent', 'admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True, help_text='Contenu du message (max 2000 caractères)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation à laquelle appartient ce message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='core_conversation_chat',
        ),
        migrations.AlterModelTable(
            name='message',
            table='core_message_chat',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='date_dernier_message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='date_fermeture',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='priorite',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='reclamation',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='type_conversation',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='uuid',
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('signalement', 'agent', 'declarant')},
        ),
    ]
