# Generated by Django 5.2.7 on 2026-01-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude GPS de l'emplacement", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude GPS de l'emplacement", max_digits=9, null=True),
        ),
    ]
